export const actions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FETCH_BUCKETS: 'FETCH_BUCKETS',
  CREATE_BUCKET: 'CREATE_BUCKET',
  DELETE_BUCKET: 'DELETE_BUCKET',
  FETCH_LIST: 'FETCH_LIST',
  FETCH_BUCKET_DOMAIN: 'FETCH_BUCKET_DOMAIN',
  FETCH_BUCKET_ZONE: 'FETCH_BUCKET_ZONE',
  DELETE_BUCKET_RESOURCE: 'DELETE_BUCKET_RESOURCE',
  MOVE_BUCKET_RESOURCE: 'MOVE_BUCKET_RESOURCE',
  CHANGE_FILE_TYPE: 'CHANGE_FILE_TYPE'
}

export const mutations = {
  SET_ACCCESS_KEY: 'SET_ACCESS_KEY',
  SET_SECRET_KEY: 'SET_SECRET_KEY',
  SET_USER_VALID: 'SET_USER_VALID',
  SET_BUCKETS: 'SET_BUCKETS',
  SET_ZONE: 'SET_ZONE',
  SET_DOMAINS: 'SET_DOMAINS',
  SET_RESOURCE_LIST_DATA: 'SET_RESOURCE_LIST_DATA',
  SET_RESOURCE_LIST_COUNT: 'SET_RESOURCE_LIST_COUNT'
}
