export const actions = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  FETCH_BUCKETS: 'FETCH_BUCKETS',
  CREATE_BUCKET: 'CREATE_BUCKET',
  DELETE_BUCKET: 'DELETE_BUCKET',
  FETCH_LIST: 'FETCH_LIST',
  FETCH_BUCKET_DOMAIN: 'FETCH_BUCKET_DOMAIN'
}

export const mutations = {
  SET_ACCCESS_KEY: 'SET_ACCESS_KEY',
  SET_SECRET_KEY: 'SET_SECRET_KEY',
  SET_USER_VALID: 'SET_USER_VALID',
  SET_BUCKETS: 'SET_BUCKETS'
}
